FROM iomete/spark:3.2.1.0
COPY target/scala-2.12/data-compaction-job-assembly-0.1.1.jar /opt/spark/jars/data-compaction-job-assembly-0.1.1.jar
COPY src/main/docker/docker_files/log4j.properties /etc/iomete/conf/